{% set name = "pymeos" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0ceaeb1886f87c6cfb4fc0af66798600ac2ef27ed585ee81bd977c90ab8065d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.7
    - setuptools >=61.0
    - pip
  run:
    - python >3.7
    - pymeos-cffi >=1.1.0,<2
    - python-dateutil
    - shapely

test:
  imports:
    - pymeos
  commands:
    - pip check
    - python -c "import pymeos; pymeos.pymeos_initialize('UTC'); pymeos.pymeos_finalize();"
  requires:
    - pip

about:
  summary: Python wrapper for the MEOS C Library.
  description: |
    PyMEOS is a Python library exposing an object-oriented API for the MEOS C Library. It wraps all the exposed
    functions in easy-to-use classes, allowing the user to perform operations on temporal and spatiotemporal data
    in Python without having to worry about the underlying C code.
  license: PostgreSQL
  license_file: LICENSE.txt
  home: https://pymeos.readthedocs.io
  doc_url: https://pymeos.readthedocs.io
  dev_url: https://github.com/MobilityDB/PyMEOS

extra:
  recipe-maintainers:
    - Diviloper
    - estebanzimanyi
